repos:
  - repo: https://github.com/johnnymorganz/stylua
    rev: v0.20.0
    hooks:
      - id: stylua-github
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: "^test/"
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint
