name: Push to Luarocks

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  luarocks-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: LuaRocks Upload
        uses: lumen-oss/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: "scm"
          extra_luarocks_args: |
            --force
          dependencies: |
            plenary.nvim
